query repositoryInfo($login: String!, $name: String!) {
  user(login: $login) {
    repository(name: $name) {
      defaultBranchRef {
        target {
          ... on Commit {
            history {
              totalCount
            }
          }
        }
      }
    }
  }
}
